
SOPHIA_TESTS = \
	storage \
	object \
	branch \
	merge \
	limits \
	transaction \
	transaction_logless \
 	cursor \
	cursor_branch \
	cursor_merge \
	recover_log \
	recover_merge \
	recover_merge_log \
	recover_merge_logless \
	recover_branch \
	svmergeiter \
	svseaveiter \
	svindexiter \
	svindex \
	sditer \
	sdpageiter \
	sliter
#	recover_loop

include ../build/config
include ../build/test
